"""offers

Revision ID: c1aca50707c5
Revises: 
Create Date: 2022-01-24 15:48:32.140200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1aca50707c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cian_address', sa.String(length=255), nullable=True),
    sa.Column('dadata_address', sa.String(length=255), nullable=True),
    sa.Column('fias', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=255), nullable=True),
    sa.Column('cargo_lifts_count', sa.SmallInteger(), nullable=True),
    sa.Column('passenger_lifts_count', sa.SmallInteger(), nullable=True),
    sa.Column('access_type', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.String(length=255), nullable=True),
    sa.Column('material_type', sa.String(length=255), nullable=True),
    sa.Column('heating_type', sa.String(length=255), nullable=True),
    sa.Column('floors_count', sa.SmallInteger(), nullable=True),
    sa.Column('land_area', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('land_area_unit_type', sa.String(length=255), nullable=True),
    sa.Column('land_type', sa.String(length=255), nullable=True),
    sa.Column('land_status', sa.String(length=255), nullable=True),
    sa.Column('is_apartments', sa.Boolean(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('raion_id', sa.Integer(), nullable=True),
    sa.Column('raion_name', sa.String(length=255), nullable=True),
    sa.Column('street_id', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(length=255), nullable=True),
    sa.Column('house_name', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_type', sa.String(length=255), nullable=True),
    sa.Column('isCianPartner', sa.Boolean(), nullable=True),
    sa.Column('isSubAgent', sa.Boolean(), nullable=True),
    sa.Column('cianProfileStatus', sa.String(length=255), nullable=True),
    sa.Column('isPassportVerified', sa.Boolean(), nullable=True),
    sa.Column('isHidden', sa.Boolean(), nullable=True),
    sa.Column('account_type', sa.Enum('realtor', 'agency', 'uk', 'owner', 'specialist', 'managementCompany', 'rentDepartment', 'anunimus-dolboebus', name='acc_type'), nullable=True),
    sa.Column('trust', sa.Enum('involved', 'notInvolved', 'new', 'excluded', 'danger', name='trust'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cianUserId', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=4095), nullable=True),
    sa.Column('creationDate', sa.Date(), nullable=True),
    sa.Column('editDate', sa.Date(), nullable=True),
    sa.Column('added', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('office', 'shoppingArea', 'flat', 'freeAppointmentObject', 'newBuildingFlat', 'dailyFlat', 'business', 'building', name='block_type'), nullable=True),
    sa.Column('dealType', sa.Enum('rent', 'sale', name='deal_type'), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('is_status_set', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.Enum('rur', 'usd', 'eur', name='cur'), nullable=True),
    sa.Column('paymentPeriod', sa.Enum('monthly', 'annual', name='payment_period'), nullable=True),
    sa.Column('floorNumber', sa.SmallInteger(), nullable=True),
    sa.Column('floorsCount', sa.SmallInteger(), nullable=True),
    sa.Column('roomsCount', sa.SmallInteger(), nullable=True),
    sa.Column('totalArea', sa.DECIMAL(precision=9, scale=2), nullable=True),
    sa.Column('fairplay', sa.Boolean(), nullable=True),
    sa.Column('isPro', sa.Boolean(), nullable=True),
    sa.Column('isAuction', sa.Boolean(), nullable=True),
    sa.Column('isInResults', sa.Boolean(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('priceType', sa.Enum('squareMeter', 'all', name='price_type'), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('priceRur', sa.BigInteger(), nullable=True),
    sa.Column('vatPrice', sa.BigInteger(), nullable=True),
    sa.Column('minArea', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('auction_currentBet', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address_string', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['cianUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_building_id'), 'offers', ['building_id'], unique=False)
    op.create_index(op.f('ix_offers_cianUserId'), 'offers', ['cianUserId'], unique=False)
    op.create_index(op.f('ix_offers_is_status_set'), 'offers', ['is_status_set'], unique=False)
    op.create_table('phones',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'phone')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('auction_curentBet', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_offer_id'), 'bets', ['offer_id'], unique=False)
    op.create_table('history_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id', 'time')
    )
    op.create_table('history_promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('services', sa.Enum('free', 'paid', 'colorized', 'premium', 'top3', name='promo'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('price_rur', sa.BigInteger(), nullable=True),
    sa.Column('price_type', sa.String(length=255), nullable=True),
    sa.Column('vat_price', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_offer_id'), 'prices', ['offer_id'], unique=False)
    op.create_table('stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stats_total', sa.SmallInteger(), nullable=True),
    sa.Column('stats_daily', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_daily')
    op.drop_index(op.f('ix_prices_offer_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_table('history_promo')
    op.drop_table('history_price')
    op.drop_index(op.f('ix_bets_offer_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_table('phones')
    op.drop_index(op.f('ix_offers_is_status_set'), table_name='offers')
    op.drop_index(op.f('ix_offers_cianUserId'), table_name='offers')
    op.drop_index(op.f('ix_offers_building_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('buildings')
    # ### end Alembic commands ###
